### ISSUE TITLE
ソースコードの.NETバージョンアップ対応

### ISSUE THREAD

**Issue by HironoBaba** [alterbooth/hol-azure-line-bot#7]
ハンズオンで使用するFunctionsの.NETのバージョンを6.0にアップデートする。

**Comment by HironoBaba** [comment]
現状のソースコードではFunctions（LINEのMessaging API部分）とWeb（LINEメッセージの管理サイト）の二部構成になっており、共通のコードが存在する。（ApplicationCore）
次回のハックツのハンズオンイベントではFunctionsの部分だけ実施予定のため、コードの切り出し＆.NETのバージョンアップ対応を行う必要がある。

**Comment by HironoBaba** [comment]
【満園さんとのミーティングメモ】
- Functionsのバージョン上げる
    -  今回のハンズオン用ブランチを作成、そちらにマージしていく（mainにはマージしない）
        - WebとApplicationCoreは削除
        - もし今後作業に不都合が生じたら別のリポジトリに移す運用
- 中島さんにハンズオンをまずやってもらい、オウム返しの時間測る
- （必要あれば）Swagger UIを使ったデバッグの手順入れる
- （手順早く終わりすぎそう&余力あれば）SQLとFunctionsバインド機能
https://learn.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-azure-sql?tabs=in-process%2Cextensionv4&pivots=programming-language-csharp
- GitHub Actionsでのデプロイを追加する作業を入れるか

**Comment by HironoBaba** [comment]
ハンズオン用ブランチ作成
https://github.com/alterbooth/hol-azure-line-bot/tree/handson-2301

**Comment by HironoBaba** [comment]
@mitsuzono 
先週松村さんとお話して、今回のハンズオンソースコードは一つのリポジトリからブランチを分けて運用するのではなく、リポジトリをフォークして分けるように指示いただきました。
そこで質問ですが、フォークするのはこちらの[hol-azure-line-bot](https://github.com/alterbooth/hol-azure-line-bot)か、
[hol-azure-line-bot-completed](https://github.com/alterbooth/hol-azure-line-bot-completed)かどちらにしましょうか？

**Comment by mitsuzono** [comment]
@HironoBaba まずは hol-azure-line-bot をフォークして、資料とハンズオン用ソースコードの準備をしてください！

hol-azure-line-bot-completed はあくまで完成サンプルですので、
資料を作成したのち今回も完成サンプルが必要となった際に、
新たに作成するか、 hol-azure-line-bot-completed からフォークしたリポジトリを新たに用意するかして準備する流れになるかと思います！

**Comment by Nakasima-K** [comment]
@mitsuzono こちらにプルリクエストを作成しました。ご確認よろしくお願いいたします。
https://github.com/alterbooth/hol-azure-line-bot/pull/8#issue-1491047729
